Exercise 18 -mohammed
FbW36/18-PB-arrays-math pull request #9
Opened 2020-10-20 12:51 UTC by mashraee

Please review my exercise number 18

2020-10-20 13:13 UTC, ciamac-da requested changes

2020-10-20 13:13 UTC, ciamac-da commented on Mohammed/index.js
> +let checkElement = isNaN(colors[randomlySelected]);
Thanks for pushing your code, actually the exercise is about to turn numbers to a empty string! So I send you the solution please take a look and push again!
const colors = ["red", 9999, "green", "blue",777, "yellow", "black", "purple", "brown"];
let colorPicker = Math.floor(Math.random() * colors.length);
let filtered = typeof colors[colorPicker] === "number" ? "" : colors[colorPicker];

2020-10-20 22:24 UTC, mashraee commented on Mohammed/index.js
> +let checkElement = isNaN(colors[randomlySelected]);
Thank you very much for reviewing my code... I made the changes and re-pushed the updated code to github

2020-10-22 07:00 UTC, ciamac-da commented on Mohammed/index.js
> +let checkElement = isNaN(colors[randomlySelected]);
Thanks

2020-10-22 07:01 UTC, ciamac-da approved these changes

2020-10-22 07:01 UTC, merged